<a href="https://colab.research.google.com/github/aksharganji23/MACHINE-LEARNING/blob/main/02FEB_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [81]:
import pandas as pd
import numpy as np
df=pd.read_csv("gender_submission.csv")
df

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [82]:
df.isnull().sum()  #checking missing values

PassengerId    0
Survived       0
dtype: int64

In [83]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
for col in df.select_dtypes(include=['object']).columns:
    df[col] = encoder.fit_transform(df[col])
df

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [84]:
import numpy as np
x=df.iloc[:,0]
y=df.iloc[:,1]
x=np.array(x).reshape(-1,1)
y=np.array(y).reshape(-1,1)
x,y

(array([[ 892],
        [ 893],
        [ 894],
        [ 895],
        [ 896],
        [ 897],
        [ 898],
        [ 899],
        [ 900],
        [ 901],
        [ 902],
        [ 903],
        [ 904],
        [ 905],
        [ 906],
        [ 907],
        [ 908],
        [ 909],
        [ 910],
        [ 911],
        [ 912],
        [ 913],
        [ 914],
        [ 915],
        [ 916],
        [ 917],
        [ 918],
        [ 919],
        [ 920],
        [ 921],
        [ 922],
        [ 923],
        [ 924],
        [ 925],
        [ 926],
        [ 927],
        [ 928],
        [ 929],
        [ 930],
        [ 931],
        [ 932],
        [ 933],
        [ 934],
        [ 935],
        [ 936],
        [ 937],
        [ 938],
        [ 939],
        [ 940],
        [ 941],
        [ 942],
        [ 943],
        [ 944],
        [ 945],
        [ 946],
        [ 947],
        [ 948],
        [ 949],
        [ 950],
        [ 951],
        [ 952],
        [ 953],
        

In [85]:
from sklearn.model_selection import train_test_split

In [86]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

In [87]:
from sklearn.linear_model import LogisticRegression

In [88]:
model=LogisticRegression(class_weight='balanced')

In [89]:
model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(class_weight='balanced')

In [90]:
y_pred=model.predict(x_test)

In [91]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,precision_score,f1_score,recall_score

In [92]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

Accuracy: 0.5238095238095238


In [93]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:\n",cm)
print("TP  FP")
print("FN  TN")
print(cm)

Confusion Matrix:
 [[26 24]
 [16 18]]
TP  FP
FN  TN
[[26 24]
 [16 18]]


In [94]:
from sklearn.metrics import precision_score
precision=precision_score(y_test,y_pred,zero_division=0)
print("Precision:",precision)

Precision: 0.42857142857142855


In [95]:
recall=recall_score(y_test,y_pred,zero_division=0)
print("Recall:",recall)

Recall: 0.5294117647058824


In [96]:
f1=f1_score(y_test,y_pred,zero_division=0)
print("F1 Score:",f1)

F1 Score: 0.47368421052631576
