<a href="https://colab.research.google.com/github/aksharganji23/MACHINE-LEARNING/blob/main/ML_LAB_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import pandas as pd
import numpy as np
df=pd.read_csv("gender_submission.csv")
df

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [56]:
df.head()

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [57]:
x=df.PassengerId
y=df.Survived
print(x,y)

0       892
1       893
2       894
3       895
4       896
       ... 
413    1305
414    1306
415    1307
416    1308
417    1309
Name: PassengerId, Length: 418, dtype: int64 0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64


In [58]:
x = df.iloc[:,:-1]  #all cloumns except last
y= df.iloc[:,-1]  #;last cloumn

In [59]:
x=np.array(x).reshape(-1,1)
y=np.array(y).reshape(-1,1)
x,y

(array([[ 892],
        [ 893],
        [ 894],
        [ 895],
        [ 896],
        [ 897],
        [ 898],
        [ 899],
        [ 900],
        [ 901],
        [ 902],
        [ 903],
        [ 904],
        [ 905],
        [ 906],
        [ 907],
        [ 908],
        [ 909],
        [ 910],
        [ 911],
        [ 912],
        [ 913],
        [ 914],
        [ 915],
        [ 916],
        [ 917],
        [ 918],
        [ 919],
        [ 920],
        [ 921],
        [ 922],
        [ 923],
        [ 924],
        [ 925],
        [ 926],
        [ 927],
        [ 928],
        [ 929],
        [ 930],
        [ 931],
        [ 932],
        [ 933],
        [ 934],
        [ 935],
        [ 936],
        [ 937],
        [ 938],
        [ 939],
        [ 940],
        [ 941],
        [ 942],
        [ 943],
        [ 944],
        [ 945],
        [ 946],
        [ 947],
        [ 948],
        [ 949],
        [ 950],
        [ 951],
        [ 952],
        [ 953],
        

In [60]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
print("Training samples:",x_train.shape)
print("Testing samples:",x_test.shape)

Training samples: (334, 1)
Testing samples: (84, 1)


In [61]:
from sklearn.svm import SVC
svm_linear = SVC(kernel='linear',class_weight='balanced',)
svm_linear.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(class_weight='balanced', kernel='linear')

In [62]:
y_pred = svm_linear.predict(x_test)

In [63]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(class_weight='balanced')
model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(class_weight='balanced')

In [64]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,precision_score,f1_score,recall_score

In [65]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

Accuracy: 0.39285714285714285


In [66]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:\n",cm)
print("TP  FP")
print("FN  TN")
print(cm)

Confusion Matrix:
 [[19 26]
 [25 14]]
TP  FP
FN  TN
[[19 26]
 [25 14]]


In [67]:
from sklearn.metrics import precision_score
precision=precision_score(y_test,y_pred,zero_division=0)
print("Precision:",precision)

Precision: 0.35


In [68]:
recall=recall_score(y_test,y_pred,zero_division=0)
print("Recall:",recall)

Recall: 0.358974358974359


In [69]:
f1=f1_score(y_test,y_pred,zero_division=0)
print("F1 Score:",f1)

F1 Score: 0.35443037974683544
